### ISSUE TITLE
getconn() doesn't work with NamedTupleCursor

### ISSUE THREAD

**Issue by jagt** [FSX/momoko#74]
Greetings. As the title suggests, `getconn()` doesn't play well with `NamedTupleCursor`.

Here's a test case:

``` python
import psycopg2
import momoko
from psycopg2.extras import NamedTupleCursor
from tornado.testing import AsyncTestCase, gen_test
import unittest
import os

class ConnNamedTuple(AsyncTestCase):
    def setUp(self):
        super().setUp()
        self.db = momoko.Pool(
            dsn='dbname=dbdb user=%s host=localhost port=5432' % os.environ['USER'],
            size=3,
            ioloop=self.io_loop,
            callback=self.stop,
            cursor_factory=NamedTupleCursor
        )
        self.wait()

    def tearDown(self):
        self.db.close()
        self.io_loop.close()

    @gen_test
    def test_conn_namedtuple(self):
        yield momoko.Op(self.db.getconn)

unittest.main()
```

Here's the stack trace:

```
======================================================================
ERROR: test_conn_namedtuple (__main__.ConnNamedTuple)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tornado/testing.py", line 427, in wrapper
    functools.partial(f, self), timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 389, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.4/dist-packages/tornado/concurrent.py", line 129, in result
    raise_exc_info(self.__exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 206, in handle_exception
    if runner is not None and runner.handle_exception(typ, value, tb):
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 580, in handle_exception
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/tornado/gen.py", line 529, in run
    yielded = self.gen.throw(*exc_info)
  File "tmp/conn_namedtuple.py", line 26, in test_conn_namedtuple
    yield momoko.Op(self.db.getconn)
  File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 302, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/momoko/connection.py", line 594, in io_callback
    self.callback(None)
  File "/usr/local/lib/python3.4/dist-packages/momoko/connection.py", line 640, in _ping_callback
    cursor.fetchall()
  File "/usr/local/lib/python3.4/dist-packages/psycopg2/extras.py", line 317, in fetchall
    nt = self.Record = self._make_nt()
  File "/usr/local/lib/python3.4/dist-packages/psycopg2/extras.py", line 340, in _make_nt
    return namedtuple("Record", [d[0] for d in self.description or ()])
  File "/usr/lib/python3.4/collections/__init__.py", line 338, in namedtuple
    'identifiers: %r' % name)
ValueError: Type names and field names must be valid identifiers: '?column?'

----------------------------------------------------------------------
Ran 1 test in 0.031s

FAILED (errors=1)
```

I'm on Python 3.4. pip freeze output, all are PyPI releases.

```
Momoko==1.1.2
psycopg2==2.5.2
tornado==3.2
```

I think it's easy to workaround but it's a little bit annoying. Thanks in advance.

**Comment by helminster** [comment]
Hello! It seems like the same error exists with register_hstore():

```python
Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 565, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/momoko/connection.py", line 864, in _register
        oid, array_oid = cursor.fetchone()
      File "/usr/local/lib/python3.4/dist-packages/psycopg2/extras.py", line 303, in fetchone
        nt = self.Record = self._make_nt()
      File "/usr/local/lib/python3.4/dist-packages/psycopg2/extras.py", line 340, in _make_nt
        return namedtuple("Record", [d[0] for d in self.description or ()])
      File "/usr/lib/python3.4/collections/__init__.py", line 348, in namedtuple
        raise ValueError('Encountered duplicate field name: %r' % name)
    ValueError: Encountered duplicate field name: 'oid'
```
